### ISSUE TITLE
Video and music not playing

### ISSUE THREAD

**Issue by Editz7** [Redven-Biker/XGame-Loading-Screen-FiveM#3]
When I go to load it into my server the music and video does not play.

**Comment by Razuuu** [comment]
same here, but not every yt video is playing

**Comment by DEVmiddle** [comment]
I know i have the same isuue:/

**Comment by OmarHopman** [comment]
I'm still having the same problem. Even if i redownload it and change the link, it still won't play.

**Comment by Redven-Biker** [comment]
> I'm still having the same problem. Even if i redownload it and change the link, it still won't play.

can you join the discord https://discord.gg/C3aN2bBVbB
